# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DamnVulnerableIOSApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DamnVulnerableIOSApp
  pod 'Parse'
  pod 'GoogleAnalytics'
  pod 'Realm'
  pod 'couchbase-lite-ios'
  pod 'Flurry-iOS-SDK/FlurrySDK'
  pod 'Bolts'
  

end